server:
  address: localhost
  port: 8080

property:
  public:
    path: /home/dev-service/dev-viewer/public

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/public?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: teamBEP0
  jpa:
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: validate